# example config for:
# hiding behind nginx (https://school.edu/webdav/)
# with users home-dirs in /Users/
Port      = "127.0.0.1:8080"
Root      = "/Users/%s"
Prefix    = "/webdav"
LogFile   = "STDERR"
AuditFile = "/var/log/webdav.log"
Debug     = false

DecapitalizeUserNames = true
AuthFailWindowSeconds = 300
AuthFailMaxCount      = 100

UIDAttribute = "uidNumber"

[ldap]
Base         = "dc=school,dc=edu"
Host         = "ldap.school.edu"
Port         = 389
SkipTLS      = true
BindDN       = ""
BindPassword = ""
UserFilter   = "(uid=%s)"
GroupFilter  = "(memberUid=%s)"
Attributes   = [ "uid", "uidNumber" ]
